version: "3.9"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
     ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - ".env"
    networks:
      - shortener-net

  shortener-api-server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: shortener-api-server
    ports:
      - "8080:8080"
    expose:
      - 5432
    depends_on:
      - postgres
    env_file:
      - ".env"
    environment:
      - "SHORTENER_PORT=8080"
    networks:
      - shortener-net

networks:
  shortener-net:
    name: shortener-net
    driver: bridge

volumes:
  postgresql_data:
    driver: local